# Generated by Django 4.2.9 on 2024-01-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cashondelivery',
            field=models.BooleanField(default=True),
        ),
    ]
